config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'mersen#input'
  post 'mersen/output'
  get 'mersen/output'
  get 'mersen/input'
  get 'mersen/userlist', :defaults => { :format => 'xml' }
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'mersens', to: 'mersen#show_data', as: :mersen_all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :authenticate_user!,except: [:new,:create]
    helper_method :current_user
    #before_action :require_login

    #include SessionHelper

  

    def current_user
        if session[:user_id]
          @current_user = User.find(session[:user_id])
        else
          @current_user = nil
        end
    end

    def authenticate_user!
      current_user
      redirect_to root_url unless @current_user
    end
    
    private

    def require_login
      unless signed_in?
        flash[:danger] = "You must log in"
        redirect_to :mersen_input
      end
    end
end

app/controllers/mersen_controller.rb
require 'prime'

class MersenController < ApplicationController
  def input
  end

  def output
    num= params[:val].to_i
    count=0
    arr=[]
    if !(num.is_a?(Integer))
      nil
    elsif num < 0 
      nil
    else
    1.upto(num) do |s|
      temp=mersen?(s)
      if Prime.prime?(s)==true and temp>0 and Prime.prime?(temp)==true
        arr.push([count+=1, s])
      end
    end
    end
    @result = arr
    @count = count
  end

  def show_data
    result = User.all.map { |element| [in: element.email, out: element.login] }
    
    respond_to do |format|
      format.html
      format.json { render xml: result.to_json }
      format.xml { render xml: result.to_xml }
    end
  end

  private

  def mersen?(n)
    m=0
    if (n+1).to_s(2).count('1') == 1
      m=(n+1).to_s(2).count('0')
    end
    return m
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
    else
      flash.now[:alert] = "Incorrect login or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :login, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mersen_helper.rb
module MersenHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lb12</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mersen/input.html.erb
<% if current_user %>
  Log in as <%= current_user.email %>.
  <%= link_to "Logout", logout_path %>
  <p id="notice"><%= notice %></p>
    <br/>
    <p>Show another users</p>
    <%= link_to 'Users', users_path %>
    <br/>
    <br/>
    <p>Числами Мерсена являются такие простые натуральные числа, которые можно записать в виде 2^p-1, где p-это тоже простое натуральное число</p>
    <p>Введите натуральное число, чтобы найти все числа меньше его, являющиеся числами Мерсена</p>
    <%= form_tag("/mersen/output", :method => "get") do %>
        <%= label_tag("Value:") %>
        <%= text_field_tag(:val)%> <br/>
        <br/>
        <%= submit_tag("Find numbers") %>
    <% end %>
    <p><%= link_to t(:Show_as_xml), mersen_all_url(format: :xml) %></p>
<% else %>
    <p>Чтобы пользоваться программой необходимо быть авторизованным</p>
    <p>Пожалуйста создайте новую учетную запись или войдите в уже существующую.</p>
    <%= link_to "Sign up", signup_path %> или
    <%= link_to "Login", login_path %>
<% end %>

app/views/mersen/output.html.erb
<h1>Mersen#output</h1>
 <p>Finded numbers</p>

<p id="count">
    <% if @result.empty? %>
        <%= 'Error input' %>
    <% else %>
        <%= "Count: #{@count}"%>
    <% end %>
</p>

<p id="res_table"></p>
<table border="1">
    <tr>
        <th>№</th>
        <th>Numbers</th>
    </tr>
    <% @result.each do |row| %>
    <tr>
        <% row.each do |value| %>
        <td>
            <%= value %>
        </td>
        <% end %>
    </tr>
    <% end %>
</table>

<p> <%= link_to "Input another value:", :mersen_input %> </p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Look', @user %> |
<%= link_to 'Back', :mersen_input %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Look at', user %></td>
        
            <td><%= link_to 'Change', edit_user_path(user) %></td>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       
        <% if current_user == user %> 
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- <%= link_to 'New user', new_user_path %>-->
<%= link_to 'Back', :mersen_input %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', :mersen_input %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Change', edit_user_path(@user) %> 

<% if current_user == @user %>
<% end %>

<%= link_to 'Back', :mersen_input %>